### ISSUE TITLE
Criteria on Rule Selection

### ISSUE THREAD

**Issue by MighTguY** [renekrie/querqy#32]
Currently if for 1 search term, there can be cases for multiple rules get selected and getting applied.
So in the updated part, User can choose which rules can be applied, by adding filtering, sorting and selection criteria.
For ex: for a search term "black shoes", there can be multiple rules.
In that case, the user can provide the criteria in URL to solr as:
    Sorting criteria: "rules.criteria.sort": "priority desc"
    multiple Filter criteria: "rules.criteria.filter": "active:true"
    Selection criteria i.e after applying filter & sorting there can be multiple rules, so if the user wants to apply top n rules, they can mention that as "rules.criteria.size": "1",

**Comment by renekrie** [comment]
Thank you for this pull request - it looks like a lot of work! I hope to review it this week.

Just to understand the need for these features a bit better: I can see the need for rule ordering but I'm struggling a bit with filtering and limiting the rules: "rules.criteria.filter": "active:true" - couldn't this be handled by deploying new set of rules that doesn't include inactive rules or by having two Querqy query parsers with two different set of rules? Also, what would be an example of a use case that requires limiting the number of rules to be applied and just pick one?

I'm not putting these features under question but having an idea of the motivation behind them will help maintaining them ;-)

**Comment by MighTguY** [comment]
Sure, The reason I put filters is there are cases that for example, some rules are applicable for the only certain property like category. An example in e-commerce space I have multiple Rules for search terms like Christmas(Category: occasion), Christmas Apparels(category: Apparel), Christmas Trees(Category: decor), sweets(Category: Food) etc. and If the user searched for Sweet Christmas Dress, we wish to only apply the rules which have the category: apparel only. 

In such cases, we can use rules.criteria.filter

Now for rules.criteria.size, If I just want to apply the top matching rule, which has the highest priority or top k rules which are above the threshold priority. In those cases, we will be needing rules.criteria.size

**Comment by MighTguY** [comment]
Hi @renekrie, I have raised 3 different pull request. 
First one https://github.com/renekrie/querqy/pull/37: This is to just add getter and setter of ruleIds in the `DismaxSearchEngineRequestAdapter.java`

Second one : https://github.com/renekrie/querqy/pull/38: This includes the changes for the querqy-core, I have created a separate request for querqy-core and querqy-solr , since querqy-solr is depending upon the querqy-core.

I have one suggestion can we make all of these 3 modules in SYNC? this will help in reducing the version coupling.

I have incorporated point **c** and point **a** in these.

For the information(Meta) I will be raising another PR.


@sachinlala

**Comment by renekrie** [comment]
I suggest the following changes to the rules.txt format. Main ideas:

* The 'old' format can still be used (not deprecated)
* Ease of use (humans can read and write it fairly easily)
* Flexibility - allow for complex rule selection and allow for data types other than String

~~~
input1 =>
   @_id: "1"
   @priority: 2
   @group: "1"
   SYNONYM: syn1

input2 =>
    @{
        "_id": "2",
        "_validFrom": "2018-12-23T08:15:43.301Z",
        "_validTo": "2019-02-22T18:00:00.00Z",
        "group": "1",
        "priority": 1,
        "categories": [
            "Electronics",
            "DIY"
        ]
    }
    SYNONYM: syn2
~~~

* No property is mandatory.
* Properties are marked by `@`
* Properties can be specified one per line (see input1), or as a complex object - maybe just as a nested map - in JSON format (input2)
* The scope is the current group of rules which was started by a previous line containing `<input> =>` and which will end at the beginning of the next group or at the EOF.
* Properties can be places anywhere within the group of rules (before, after, mixed with rules) 
* Properties can be typed, so that ordering by a property can use the index order of the data type (see integer values for priority properties in the example)
* Some property names have a meaning within Querqy, others can be defined and used freely. Properties that have a meaning within Querqy will have a prefix `_` to their name. For now, I think about giving property names `_id`, `_validFrom` and `_validTo` a special meaning in Querqy. In order not to spend too much time on implementation now, I would only use `_id` for now, when we return the applied rules together with the response.
* Property selection at query time could use  [JSONPath](https://github.com/json-path/JsonPath) (still to be tested). 

In order to close this PR soon, we can start by using the one-per-line format and support string properties only.

Looping in @MighTguY, @pbartusch @mkr for comment.

**Comment by MighTguY** [comment]
Hi @renekrie,  Can we make some of the properties mandatory like the id and priority although we can internally set priority to default INTEGER_MIN. but I think Id is better to have so that it will also help us while reconciling the output and to trace the rules,

**Comment by renekrie** [comment]
Hi @MighTguY,

Thanks for commenting. 

I would like to keep things non-mandatory so that rules.txt can be edited easily by humans (= avoid worrying about ID uniqueness) and also for backward compatibility. 

If your worry re ID is traceability: I've given instructions an implicit property 'ord'. This is an ordinal which represents the loading order of the rules. For traceability we could use something like '#<ord>' in the output ('#2' would then be rule number 2 in your rules.txt - or ore precisely, it would be the 3rd rule as ord is 0-based, but that could be changed ). I'm already using ord as a secondary sort criterion (in case someone assigns the same priority twice, we will still have a stable order). Also, in the ConfigurationOrderSelectionStrategy (which doesn't know about criteria) rules will be sorted by ord.
However, as the order of rules might change, using ord only helps a bit - but then people can simple add an ID property (it will be their responsibility).

Re traceability: Alternatively, I wonder whether we should add a property `@_traceTag` (maybe multi-valued), so that users could add any tracing info they need in the response (could be the ID or any tag value they want to track).

**Comment by renekrie** [comment]
Implemented. See https://github.com/renekrie/querqy/#rule-properties-rule-ordering-and-rule-filtering for documentation
